### ISSUE TITLE
Question - What is the intent of `Curated List of Tools` section ?

### ISSUE THREAD

**Issue by venkyvb** [berndruecker/processautomationbook.com#9]
Just wanted to check as to what was the original intention of the page - `Curated List of Tools` ? Since there is nothing right now, I was thinking if it would make sense to give some links to interesting WF engines.

**Comment by berndruecker** [comment]
Yes - this was definitely the intent of that page!
When I started to create it, I started thinking about how to approach this and how to list tools without being too opinionated - and somehow this distracted me to write this: https://www.infoworld.com/article/3617928/understanding-the-process-automation-landscape.html and I lost track of writing that page. Thanks for the reminder - I'll put it back on my agenda/list (but are a bit busy the next weeks)
